In [2]:
import numpy as np
import pandas as pd
import os
import shutil

In [3]:
stock = pd.read_csv("data/stock data top 100 tech company 2019_11_1.csv")

In [4]:
stock

,Symbol,Name,Price (Intraday),Change,% Change,Volume,Avg Vol (3 month),Market Cap,PE Ratio (TTM),52 Week Range
0,AAPL,Apple Inc.,255.82,7.06,2.84%,37.781M,80.881M,1.156T,21.52,NaN
1,MSFT,Microsoft Corporation,143.72,0.35,0.24%,33.128M,62.051M,1.096T,27.12,NaN
2,GOOG,Alphabet Inc.,"1,273.74",13.63,1.08%,1.67M,3.515M,878.025B,27.33,NaN
3,GOOGL,Alphabet Inc.,"1,272.25",13.45,1.07%,1.091M,3.737M,877.91B,27.3,NaN
4,FB,"Facebook, Inc.",193.62,1.97,1.03%,21.712M,78.021M,552.388B,30.95,NaN
...,...,...,...,...,...,...,...,...,...,...
95,LYFT,"Lyft, Inc.",42.98,1.54,3.72%,7.497M,31.893M,12.79B,NaN,NaN
96,PAGS,PagSeguro Digital Ltd.,37.17,0.09,0.24%,2.703M,8.781M,12.223B,53.41,NaN
97,PAYC,"Paycom Software, Inc.",214.31,2.78,1.31%,"432,577",1.656M,12.356B,75.09,NaN
98,TDY,Teledyne Technologies Incorporated,336.15,6.55,1.99%,"171,656","500,233",12.259B,33.25,NaN
99,LDOS,"Leidos Holdings, Inc.",85.33,-0.90,-1.04%,"935,512",3.61M,12.08B,18.59,NaN

In [5]:
type(stock)

pandas.core.frame.DataFrame

In [13]:
Name_list = list(stock['Symbol'])
Name_list

['AAPL',
 'MSFT',
 'GOOG',
 'GOOGL',
 'FB',
 'TSM',
 'INTC',
 'CSCO',
 'ORCL',
 'SAP',
 'CRM',
 'ADBE',
 'NVDA',
 'IBM',
 'ACN',
 'AVGO',
 'ASML',
 'TXN',
 'QCOM',
 'SNE',
 'INTU',
 'VMW',
 'MU',
 'UBER',
 'AMAT',
 'NOW',
 'ATVI',
 'INFY',
 'ADI',
 'LRCX',
 'AMD',
 'DELL',
 'WDAY',
 'NTES',
 'SHOP',
 'BIDU',
 'CTSH',
 'ADSK',
 'NXPI',
 'TEL',
 'APH',
 'TEAM',
 'ERIC',
 'EA',
 'MSI',
 'KLAC',
 'SQ',
 'HPQ',
 'SPOT',
 'FLT',
 'FTV-PA',
 'FTV',
 'XLNX',
 'MCHP',
 'TME',
 'TWTR',
 'GLW',
 'PANW',
 'VRSN',
 'HPE',
 'VEEV',
 'SNAP',
 'GIB',
 'CERN',
 'STM',
 'MTCH',
 'SNPS',
 'IAC',
 'KEYS',
 'SPLK',
 'CDW',
 'ANSS',
 'CDNS',
 'GRMN',
 'CHKP',
 'SWKS',
 'MRVL',
 'MXIM',
 'WDC',
 'FTNT',
 'STX',
 'SSNC',
 'SYMC',
 'CTXS',
 'ANET',
 'AKAM',
 'IT',
 'NTAP',
 'RNG',
 'OKTA',
 'SE',
 'TTWO',
 'TWLO',
 'ZBRA',
 'IQ',
 'LYFT',
 'PAGS',
 'PAYC',
 'TDY',
 'LDOS']